### ISSUE TITLE
The browser accesses the RPC port

### ISSUE THREAD

**Issue by rootdoc** [HcashOrg/hcd#13]
2018/08/21 15:30:04 http: TLS handshake error from 192.168.1.173:52104: tls: first record does not look like a TLS handshake
2018/08/21 15:30:14 http: TLS handshake error from 192.168.1.173:52105: read tcp4 192.168.1.107:19109->192.168.1.173:52105: i/o timeout

Why?

**Comment by hunjixin** [comment]
maybe a https cert you need

**Comment by rootdoc** [comment]
What should I do？

**Comment by coolsnady** [comment]
you can use gencerts tools to make a cert file for rpc call.

rootdoc <notifications@github.com> 于2018年8月25日周六 上午9:07写道：

**Comment by rootdoc** [comment]
The rpc.cert certificate was added to the browser, but it still is

**Comment by coolsnady** [comment]
you should put it into .hcd directory instead of adding browser.

rootdoc <notifications@github.com> 于2018年9月4日周二 下午4:00写道：
