### ISSUE TITLE
blockchain has syncd, but api getblockcount return 0

### ISSUE THREAD

**Issue by zhiquan911** [HcashOrg/hcd#3]
Network: testnet
We blockchain has synced completed.
The json-rpc api call "getinfo" return blocks is 1019, but call getblockcount return 0.

**Comment by coolsnady** [comment]
Hi,
you can get correct block height  from hcd json-rpc server.
you can git pull and try again if it doesn't work.


2018-08-03 18:37 GMT+08:00 Chance <notifications@github.com>:
