### ISSUE TITLE
about pow mining

### ISSUE THREAD

**Issue by wangjunasd** [HcashOrg/hcd#5]
I used decred function to submit blockhex on testnet and  the return  ：
Block submitted via getwork rejected: invalidate extradata.

extradata is 8000000100000000000005a0

**Comment by coolsnady** [comment]
Hi,
Thanks for your email.
Yes.We added some feature.
we will send you details ASAP

Best regards

HyperCash Dev

2018-08-06 1:45 GMT+08:00 Wangjun <notifications@github.com>:

**Comment by goodthebest** [comment]
@wangjunasd @coolsnady I'm also getting the same error, @wangjunasd did you find a solution?

**Comment by goodthebest** [comment]
hey @waitkeeper can you please look into this? I'm getting this error while mining HC
`Block submitted via getwork rejected: invalidate extradata`
