### ISSUE TITLE
deriving additional addresses violates the unused address gap limit

### ISSUE THREAD

**Issue by prettyCoders** [HcashOrg/hcd#67]
![image](https://user-images.githubusercontent.com/36216120/59986047-7b8ac280-9667-11e9-98ce-3e29fe118200.png)

**Comment by zl03jsj** [comment]
i got the same problem..

**Comment by zl03jsj** [comment]
@prettyCoders the second param is 'gappolicy', set it to 'ignore' will solve the problem

**Comment by TriRikkie** [comment]
please refer to hcomniEngine rpc code
https://github.com/HcashOrg/hcOmniEngine/blob/f1acc2ba3640a8e1c651ddc90a86d569d00704fe/rpcclient.py#L33
