### ISSUE TITLE
getaccountaddress "default" shows address next by getnewaddress

### ISSUE THREAD

**Issue by crcrcr999** [HcashOrg/hcd#7]
if use  `hcctl --wallet getaccountaddress "default"` will show an address ,but if use `hcctl --wallet getaddressesbyaccount "default" `it will not show the address ,like:

`hcctl --wallet getaccountaddress "default"`
`HsUASZhY6zuKiSmsrAzRT2MeuuZwiMSrQA7`

and then:

`hcctl --wallet getaddressesbyaccount "default"`
`[
  "HsWs21CP9MMqg4j3e3QSnYZDBKzXSqjhjqA",
  "HsUesTiQZzUCg5WPebxYPexEWNbHUAES571",
  "HsG5BnENoRrke6jvqPPDptEw2xpCfmjhJQ4"
]`

it's not in the default account,but if you use 

`hcctl --wallet getnewaddress`
`HsUASZhY6zuKiSmsrAzRT2MeuuZwiMSrQA7`

and now if you use the 

`hcctl --wallet getaddressesbyaccount "default"`
`[
  "HsWs21CP9MMqg4j3e3QSnYZDBKzXSqjhjqA",
  "HsUesTiQZzUCg5WPebxYPexEWNbHUAES571",
  "HsG5BnENoRrke6jvqPPDptEw2xpCfmjhJQ4",
  "HsUASZhY6zuKiSmsrAzRT2MeuuZwiMSrQA7"
]`

the address is in the account.
the same issues shows as use hcctl --wallet getaccountaddress "postquantum" and getnewaddress "postquantum"

**Comment by hunjixin** [comment]
in fact getaccountaddress is used to get the future address in the account, and getnewaddress will change the end position in the address buffer

**Comment by crcrcr999** [comment]
ok
