### ISSUE TITLE
can not send coin

### ISSUE THREAD

**Issue by prettyCoders** [HcashOrg/hcd#72]
{"result":null,"error":{"code":-32603,"message":"-1: Rejected transaction 9d5a41c22cc57d74629fc1e754ec8eb391d30a1907e8088765bb44ef286fb508: orphan transaction 9d5a41c22cc57d74629fc1e754ec8eb391d30a1907e8088765bb44ef286fb508 references outputs of unknown or fully-spent transaction d148e279fa5b6df22f2d473623a140f6f1d9617cd4548c02713e7cac95081a24"},"id":"curltest"}

**Comment by prettyCoders** [comment]
![image](https://user-images.githubusercontent.com/36216120/63563749-c4da8e00-c594-11e9-8f18-0ccaeb27bbbd.png)

**Comment by GladysKellogg** [comment]
maybe you should send after the wallet rescanning the best block
